global:
  controlPlaneSecurityEnabled: true
  mtls:
    enabled: true

  outboundTrafficPolicy:
    mode: REGISTRY_ONLY

  proxy:
    accessLogFile: "/dev/stdout"
    envoyStatsd:
      enabled: false

  configValidation: true
  useMCP: false

certmanager:
  enabled: true

gateways:
  enabled: true
  istio-ingressgateway:
    autoscaleEnabled: false
    enabled: true
    resources:
      requests:
        cpu: 10m
        memory: 40Mi

  istio-egressgateway:
    autoscaleEnabled: false
    enabled: false
    resources:
      requests:
        cpu: 10m
        memory: 40Mi

# security:
#   enabled: false

galley:
  enabled: true

mixer:
  policy:
    enabled: false
  telemetry:
    enabled: false

pilot:
  enabled: true
  sidecar: false

prometheus:
  enabled: false

sidecarInjectorWebhook:
  enabled: true
  rewriteAppHTTPProbe: true


