apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ksample
  namespace: sample
spec:
  template:
    spec:
      containers:
      - image: kennethreitz/httpbin
        name: ksample
        ports:
        - containerPort: 80
