apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: egw
  namespace: sample
spec:
  selector:
    istio: egressgateway
  servers:
  - hosts:
    - "*"
    port:
      name: https
      number: 80
      protocol: HTTPS
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: httpbin
  namespace: sample
spec:
  hosts:
  - httpbin.org
  location: MESH_EXTERNAL
  ports:
  - name: https
    number: 443
    protocol: HTTPS
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: egw
  namespace: sample
spec:
  gateways:
  - egw
  - mesh
  hosts:
  - httpbin.org
  http:
  - match:
    - gateways:
      - egw
      port: 80
    route:
    - destination:
        host: httpbin.org
        port:
          number: 443
        weight: 100
  - match:
    - gateways:
      - mesh
      port: 80
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: httpbin
        port:
          number: 80
        weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egw
  namespace: sample
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
  - name: httpbin
    trafficPolicy:
      portLevelSettings:
      - port:
          number: 80
        tls:
          mode: ISTIO_MUTUAL
          sni: httpbin.org
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: httpbin
  namespace: sample
spec:
  host: httpbin.org
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 443
      tls:
        mode: SIMPLE
        sni: httpbin.org


