apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: authn
  namespace: testing
spec:
  targets:
    - name: nginx
  peers:
    - mtls: {}
  origins:
    - jwt:
        issuer: "banking-auth-provider"
        jwksUri: "https://coretech-jwks-dev.s3-ap-southeast-2.amazonaws.com/banking/.well-known/jwks.json"
        jwtHeaders: ["X-Banking-Authorization"]
  principalBinding: USE_ORIGIN
